[project]
name = "counter-app"
description = "A simple counter smart contract for Stacks blockchain"
authors = ["oluwagbemiga <oluwagbemigagbangbola@gmail.com>"]
telemetry = true
cache_dir = "./.cache"

[contracts.counter-v3]
path = "contracts/counter.clar"
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

